# Generated by Django 2.1.1 on 2018-09-01 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propietarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=10)),
                ('tipo_vehiculo', models.CharField(max_length=10)),
                ('id_propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propietarios.Propietario')),
            ],
        ),
    ]
