# Generated by Django 2.1.1 on 2018-09-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='marca',
            new_name='modelo',
        ),
    ]
